[package]
name = "wgpu-cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = { version = "0.112.0", features = ["jit", "module", "native"] }
cranelift-object = "0.112.1"
naga = "22.1.0"
raw-window-handle = "0.6.2"
wgpu = "22.1.0"
wgpu-hal = "22.0.0"
wgpu-types = "22.0.0"
